name: Install dependencies
description: Installs and caches dependencies

runs:
  using: composite
  steps:
    - name: Setup Node@14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: |
        if [ ! -d ./node_modules ]; then
          yarn install --immutable
        else
          echo package.json and yarn.lock unchanged. Using cache.
        fi
