name: Install dependencies
description: Installs and caches dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache root node modules step
      uses: actions/cache@v3
      with:
        path: node_modules/*
        key: node_modules-node-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ ! -d ./node_modules ]; then
          yarn install --immutable
        else
          echo package.json and yarn.lock unchanged. Using cache.
        fi
