name: Test

on: push

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/install-dependencies
      - uses: ./.github/actions/static-check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/install-dependencies
      - uses: ./.github/actions/unit-tests
